const GROCERIES = [
	'MARLOW & DAUGHTERS',
	'MR PINA',
  'BROOKLYN HARVEST',
  'BROOKLYN FARE GREENWICH',
  'BROOKLYN HARVEST',
  'MET FOOD',
]

const INTEREST = [
	'Interest Charge on Purchases',

]

const PERSONAL = [
  'WALGREENS',
  'SI LAUNDROMAT & DRY CLEA',
  'HUDSON SQUARE PHARMACY',
  'WHISK',
  'LEVI.COM'
]

const TRANSPORT = [
  'METROCARD MACHINE NEW YORK NY'
]

const EATING_OUT = [
  'BAGEL ON THE SQUARE',
  'HAVE A BAGEL',
  'Shake Shack',
  'RESTAURANT',
  'GRILL',
  'COFFEE'
];

const ALCOHOL = [
  'GRAIN & VINE',
  'THE LATE LATE'
]

const UTILITIES = []
const TRAVEL = ['DELTA AIR LINES']
const ENTERTAINMENT = []
const VENMO = [];
const OTHER = [];
const CASH_WITHDRAWAL = [];
const RENT = [];

const CATEGORIES = [
	'RENT',
	'GROCERIES',
	'EATING_OUT',
	'CASH_WITHDRAWAL',
	'TRANSPORT',
	'ALCOHOL',
	'ENTERTAINMENT',
	'UTILITIES',
	'TRAVEL',
	'INTEREST',
	'VENMO',
	'PERSONAL',
	'OTHER'
];

const CATEGORY_MAP = {
  GROCERIES,
  INTEREST,
  PERSONAL,
  TRANSPORT,
  RENT,
  EATING_OUT,
  ALCOHOL,
  UTILITIES,
  TRAVEL,
  ENTERTAINMENT,
  VENMO,
  OTHER,
  CASH_WITHDRAWAL
}

module.exports = { CATEGORIES, CATEGORY_MAP };