const GROCERIES = [
	'MARLOW & DAUGHTERS',
	'MR PINA',
  'BROOKLYN HARVEST',
  'BROOKLYN FARE GREENWICH',
  'BROOKLYN HARVEST',
  'MET FOOD',
]

const INTEREST = [
	'INTEREST CHARGE ON PURCHASES',
]

const PERSONAL = [
  'WALGREENS',
  'SI LAUNDROMAT & DRY CLEA',
  'HUDSON SQUARE PHARMACY',
  'WHISK',
  'LEVI.COM',
  'CLOTHING',
  'APPAREL'
]

const TRANSPORT = [
  'METROCARD MACHINE NEW YORK NY',
  'METROCARD'
]

const EATING_OUT = [
  'BAGEL ON THE SQUARE',
  'HAVE A BAGEL',
  'SHAKE SHACK',
  'RESTAURANT',
  'GRILL',
  'COFFEE',
  'SEAMLSS'
];

const ALCOHOL = [
  'GRAIN & VINE',
  'THE LATE LATE',
  'ALE'
]

const UTILITIES = []
const TRAVEL = ['DELTA AIR LINES']
const ENTERTAINMENT = ['SPOTIFY', 'SOFAR']
const VENMO = ['VENMO'];
const OTHER = [];
const CASH_WITHDRAWAL = [];
const RENT = [];

const EXPENSE_CATEGORIES = [
	'RENT',
	'GROCERIES',
	'EATING_OUT',
	'CASH_WITHDRAWAL',
	'TRANSPORT',
	'ALCOHOL',
	'ENTERTAINMENT',
	'UTILITIES',
	'TRAVEL',
	'INTEREST',
	'VENMO',
	'PERSONAL',
	'OTHER'
];

const EXPENSE_CATEGORY_MAP = {
  GROCERIES,
  INTEREST,
  PERSONAL,
  TRANSPORT,
  RENT,
  EATING_OUT,
  ALCOHOL,
  UTILITIES,
  TRAVEL,
  ENTERTAINMENT,
  VENMO,
  OTHER,
  CASH_WITHDRAWAL
}

module.exports = { 
  EXPENSE_CATEGORIES,
  EXPENSE_CATEGORY_MAP
};